title: NightmareXIV
description: Game plugins and commissions
theme: just-the-docs

url: https://nightmarexivtest.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

