title: NightmareXIV
description: Game plugins and commissions
theme: just-the-docs

url: https://nightmarexivtest.github.io

aux_links:
  Discord: https://discord.gg/m8NRt4X8Gf
  Patreon: https://www.patreon.com/NightmareXIV

search_enabled: false
color_scheme: dark

callouts:
  warning:
    title: Warning
    color: red